# version: '3.8'

services:
  flume:
    image: probablyfine/flume
    volumes:
      - ./api/src/flume:/opt/flume/conf
      - ./api/src/simulation:/opt/flume/data
    command: ["agent", "-n", "exposure_logs_agent", "-c", "/opt/flume/conf", "-f", "/opt/flume/conf/flume.conf"]
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:3
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:3
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077

  backend:
    build: ./api
    depends_on:
      - kafka
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  pgdata: